package com.springboard.hackathongo.entities;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import java.math.BigInteger;
import java.util.Date;

@Data
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "account")
public class Account {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private int id;

    @DynamoDBAttribute
    private int cabinNumber;

    @DynamoDBAttribute
    private Long phone;

    @DynamoDBAttribute
    private String services;

    @DynamoDBAttribute
    private Date dob;

    @DynamoDBAttribute
    private String firstName;

    @DynamoDBAttribute
    private String lastName;

    @DynamoDBAttribute
    private String provider;

    @DynamoDBAttribute
    private String case_mgr;

    @DynamoDBAttribute
    private String need;
}
