package com.springboard.hackathongo.entities;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.Date;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@Data
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "activity")
public class Activity {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private int id;

    @DynamoDBAttribute
    private String activityFeed;

    @DynamoDBAttribute
    private Date date;

    @DynamoDBAttribute
    private int sqnId;

    @DynamoDBAttribute
    private String description;
}
