package com.springboard.hackathongo.entities;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "comments")
public class Comments {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private int id;

    @DynamoDBAttribute
    private int serviceId;

    @DynamoDBAttribute
    private int userId;

    @DynamoDBAttribute
    private int destinationId;

    @DynamoDBAttribute
    private String comment;
}
