package com.springboard.hackathongo.entities;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "service_table")
public class Services {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private int serviceType;

    @DynamoDBAttribute
    private String url;

    @DynamoDBAttribute
    private String enrolledAccounts;//long string on account pk's

    @DynamoDBAttribute
    private String description;

    @DynamoDBAttribute
    private String category;

    @DynamoDBAttribute
    private int cabinNumber;
}
