package com.springboard.hackathongo.entities;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.Date;

@Data
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "usr_table")
public class Users {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private int sqnId;

    @DynamoDBAttribute
    private String role;

    @DynamoDBAttribute
    private String enrollment;

    @DynamoDBAttribute
    private String acceptance;

    @DynamoDBAttribute
    private String userId;//log in

    @DynamoDBAttribute
    private String passwd;

    @DynamoDBAttribute
    private int accountId;

    @DynamoDBAttribute
    private Date lastUpdated;
}
